FROM alpine:latest

RUN apk update && apk upgrade && \
    apk add --no-cache bash git && \
    apk add ssh

RUN mkdir /root/.ssh \
 && touch /root/.ssh/known_hosts \
 && ssh-keyscan github.com >> /root/.ssh/known_hosts

COPY id_rsa /root/.ssh/id_rsa
RUN git clone git@github.com:shakur-sudo/siryi-homework.git
